USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS ENERGY_PROJECT;
CREATE SCHEMA IF NOT EXISTS ENERGY_PROJECT.BRONZE;
USE SCHEMA ENERGY_PROJECT.BRONZE;

-- Create the table structure again
CREATE OR REPLACE TABLE RAW_INTENSITY (
    raw_json VARIANT,
    ingested_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

USE DATABASE ENERGY_PROJECT;
USE SCHEMA BRONZE;

-- 1. Set the absolute path
USE ROLE ACCOUNTADMIN;
USE DATABASE ENERGY_PROJECT;
USE SCHEMA BRONZE;

-- 2. Run the smarter COPY command again
COPY INTO RAW_INTENSITY
FROM (
    SELECT $1, CURRENT_TIMESTAMP() 
    FROM @energy_stage
)
FILE_FORMAT = (TYPE = JSON);

-- 3. Verify it worked
SELECT COUNT(*) FROM RAW_INTENSITY;

